all:
  hosts:
    node1:
      ansible_host: 192.0.2.11
      ip: 10.20.20.11
    node2:
      ansible_host: 192.0.2.12
      ip: 10.20.20.12
    node3:
      ansible_host: 192.0.2.13
      ip: 10.20.20.13
    node4:
      ansible_host: 192.0.2.14
      ip: 10.20.20.14
    node5:
      ansible_host: 192.0.2.15
      ip: 10.20.20.15
    node6:
      ansible_host: 192.0.2.16
      ip: 10.20.20.16
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
